---
- name: apt-get update a server
  apt: update_cache=yes
  sudo: yes
  tags: initial_setup

- name: apt-get install build-essential
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
  - build-essential
  tags: install_build

- name: cuda-install
  shell: wget http://developer.download.nvidia.com/compute/cuda/6_5/rel/installers/cuda_6.5.14_linux_64.run
  sudo: yes
  tags: cuda_install

- name: cuda-process
  shell: chmod +x cuda_6.5.14_linux_64.run && mkdir -p nvidia_installers
  sudo: yes
  tags: cuda_process

- name: cuda-run
  shell: ./cuda_6.5.14_linux_64.run -extract=`pwd`/nvidia_installers 
  sudo: yes
  tags: cuda_process

- name: apt-get install basic pkg
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
  - linux-image-extra-virtual
  tags: initial_setup

- name: reboot!
  command: shutdown -r now
  sudo: yes
  ignore_errors: true
  tags: reboot

#- name: wait for SSH port down
#  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
#  tags: reboot

- name: wait for SSH port up
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10 timeout=300
  tags: reboot

- name: update blacklist-nouveau.conf 
  lineinfile: >
    dest="/etc/modprobe.d/blacklist-nouveau.conf"
    create=yes
    line="{{ item.line }}"
  with_items:
  - line: blacklist nouveau 
  - line: blacklist lbm-nouveau 
  - line: options nouveau modeset=0 
  - line: alias nouveau off 
  - line: alias lbm-nouveau off 
  sudo: yes
  tags: configure nouveau 

- name: remake nouveau 
  shell: echo options nouveau modeset=0 | sudo tee -a /etc/modprobe.d/nouveau-kms.conf 
  sudo: yes
  tags: configure nouveau 

- name: update 
  shell: update-initramfs -u 
  sudo: yes
  tags: update 

- name: reboot!
  command: shutdown -r now
  sudo: yes
  ignore_errors: true
  tags: reboot

- name: wait for SSH port down
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
  tags: reboot

- name: wait for SSH port up
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=10 timeout=300

- name: apt-get install linux 
  apt: pkg={{ item }} state=installed
  sudo: yes
  with_items:
  - linux-source 
  - linux-headers-3.13.0-37-generic 
  tags: install_linux

- name: nvidia-install
  shell: /home/ubuntu/nvidia_installers/NVIDIA-Linux-x86_64-340.29.run --no-questions -a -s 
  sudo: yes
  tags: nvidia 
